config/routes.rb
Kalfred::Application.routes.draw do
  root 'home#index'
  get "contact/index"
  get "services/index"
  get "about/index"
  get "home/index"
  post "contact/contact"

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

def show
  	@about = params[:name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
  def show
  	@contact = params[:name]
  end

  def contact
  	UserMailer.contact_email(params[:name], params[:email], params[:phone],
  		params[:message]).deliver
  	flash[:notice]= "Email Sent! Thank you!"
  	redirect_to '/'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
def show
  	@services = params[:name]
  end
end

app/controllers/user_mailer_controller.rb
class UserMailerController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/user_mailer_helper.rb
module UserMailerHelper
end

app/views/about/index.html.erb
        <!-- box content goes here if you want to put text or a button in here -->
    
    <!-- /full-width-image-2 -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12 section">
                <h1 class="section-heading">Another Interesting Headline</h1>
                <p class="lead section-lead">The two different full width images are defined in the CSS. They aren't the same! One has a defined height, and one does not! Go crazy and get creative!</p>
                <p class="section-paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin auctor quam ac tempor. Cras a ante sed libero mollis sodales. Praesent fringilla, neque ut ultrices faucibus, dolor eros ultrices neque, nec bibendum arcu ipsum eget justo. Phasellus vestibulum sagittis purus laoreet varius. Pellentesque malesuada malesuada mattis. Aliquam sed porta nisi, eget suscipit dolor. Nam ipsum sapien, rhoncus eu leo eu, ultricies pellentesque tellus.</p>
            </div>
        </div>
    </div>

    <div class="container">
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>k.alfred 2014sum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum e
                    </p>
                </div>
            </div>

        </footer>
    </div>

app/views/about/show.html.erb
<% begin %>
	<%= render @about %>
<% rescue %>
	<h1>about what???</h1>
<% end %>

app/views/contact/index.html.erb
        <!-- box content goes here if you want to put text or a button in here -->
  
    <!-- /full-width-image-2 -->



<div class="container">
        <div class="row">
            <div class="col-lg-12 section">
                <h1 class="section-heading">Another Interesting Headline</h1>
                <p class="lead section-lead">The two different full width images are defined in the CSS. They aren't the same! One has a defined height, and one does not! Go crazy and get creative!</p>
                <p class="section-paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin auctor quam ac tempor. Cras a ante sed libero mollis sodales. Praesent fringilla, neque ut ultrices faucibus, dolor eros ultrices neque, nec bibendum arcu ipsum eget justo. Phasellus vestibulum sagittis purus laoreet varius. Pellentesque malesuada malesuada mattis. Aliquam sed porta nisi, eget suscipit dolor. Nam ipsum sapien, rhoncus eu leo eu, ultricies pellentesque tellus.</p>
            </div>
        </div>
    </div>

    <div class="row">
            <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact <strong>form</strong>
                    </h2>
                    <hr>
                    <p>This contact form is just the form elements, it is not a working form. You will have to make the form work by yourself, or take it out if you can't figure out how to make it work.</p>
                    <%= form_tag('/contact/contact', role: 'form') do %>
                        <div class="row">
                            <div class="form-group col-lg-4">
                                <label>Name</label>
                                <input type="text" name='name' class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Email Address</label>
                                <input type="email" name='email' class="form-control">
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Phone Number</label>
                                <input type="tel" name='phone' class="form-control">
                            </div>
                            <div class="clearfix"></div>
                            <div class="form-group col-lg-12">
                                <label>Message</label>
                                <textarea class="form-control" name='message' rows="6"></textarea>
                            </div>
                            <div class="form-group col-lg-12">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

    </div>

<div class="container">
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>k.alfred 2014sum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum e
                    </p>
                </div>
            </div>

        </footer>
    </div>

app/views/contact/show.html.erb
<% begin %>
	<%= render @contact %>
<% rescue %>
	<h1>about what???</h1>
<% end %>

app/views/home/index.html.erb
 

 <div class="row">
            <div class="box col-md-offset-1 col-md-10">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Beautiful boxes <strong>to showcase your content</strong>
                    </h2>
                    <hr>
                    <p>Use as many boxes as you like, and put anything you want in them! They are great for just about anything, the sky's the limit!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

<div class="full-width-image-2">
        <!-- box content goes here if you want to put text or a button in here -->
    </div>
    <!-- /full-width-image-2 -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12 section">
                <h1 class="section-heading">Another Interesting Headline</h1>
                <p class="lead section-lead">The two different full width images are defined in the CSS. They aren't the same! One has a defined height, and one does not! Go crazy and get creative!</p>
                <p class="section-paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin auctor quam ac tempor. Cras a ante sed libero mollis sodales. Praesent fringilla, neque ut ultrices faucibus, dolor eros ultrices neque, nec bibendum arcu ipsum eget justo. Phasellus vestibulum sagittis purus laoreet varius. Pellentesque malesuada malesuada mattis. Aliquam sed porta nisi, eget suscipit dolor. Nam ipsum sapien, rhoncus eu leo eu, ultricies pellentesque tellus.</p>
            </div>
        </div>
    </div>
        
        <footer>
            <div class="row">
                <div class="col-lg-12">
                   <p> ctumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis
                   </p>
                </div>
            </div>

        </footer>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


<title>Kalfred</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
    
<body>
    <div class="brand"></div>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to 'HOME', home_index_path %>
                    </li>
                    <li><%= link_to 'ABOUT', about_index_path %>
                    </li>
                    <li><%= link_to 'SERVICES', services_index_path %>
                    </li>
                    <li><%= link_to 'CONTACT', contact_index_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    
    <div class="full-width-image-1">

        <div class="logo-wrapper">
            <%= image_tag('logo.jpg', size: '150x150', style: "margin-bottom: 350px") %>
        </div>
      <%= yield %>  
    </div>
    <!-- /full-width-image-1 -->

    
    <!-- FOOTER -->



    <!-- /container -->

    <!-- JavaScript -->
   
</body>

</html>

app/views/services/index.html.erb
<div class="container">
        <div class="row">
            <div class="col-lg-12 section">
                <h1 class="section-heading">Another Interesting Headline</h1>
                <p class="lead section-lead">The two different full width images are defined in the CSS. They aren't the same! One has a defined height, and one does not! Go crazy and get creative!</p>
                <p class="section-paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin auctor quam ac tempor. Cras a ante sed libero mollis sodales. Praesent fringilla, neque ut ultrices faucibus, dolor eros ultrices neque, nec bibendum arcu ipsum eget justo. Phasellus vestibulum sagittis purus laoreet varius. Pellentesque malesuada malesuada mattis. Aliquam sed porta nisi, eget suscipit dolor. Nam ipsum sapien, rhoncus eu leo eu, ultricies pellentesque tellus.</p>
            </div>
        </div>
    </div>

app/views/services/show.html.erb
<% begin %>
	<%= render @services %>
<% rescue %>
	<h1>about what???</h1>
<% end %>